#!/bin/bash

# AdSphere Python System - Complete Getting Started Guide
# Follow these steps to start using the system in 8 minutes

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   AdSphere Python System - Getting Started Guide           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Navigate to directory
echo -e "${BLUE}STEP 1: Navigate to Python System${NC}"
echo "Run this command:"
echo ""
echo "  cd /Users/danielkinyua/Downloads/projects/ad/adsphere/python_system"
echo ""
echo -e "${YELLOW}⏳ Copy and paste the above command now${NC}"
echo ""
read -p "Press Enter when you're in the python_system directory..."
echo ""

# Step 2: Create virtual environment
echo -e "${BLUE}STEP 2: Create Virtual Environment${NC}"
echo "Run this command:"
echo ""
echo "  python3 -m venv venv"
echo ""
echo -e "${YELLOW}⏳ This creates an isolated Python environment${NC}"
echo ""
read -p "Press Enter when the virtual environment is created..."
echo ""

# Step 3: Activate virtual environment
echo -e "${BLUE}STEP 3: Activate Virtual Environment${NC}"
echo "Run this command:"
echo ""
echo "  source venv/bin/activate"
echo ""
echo -e "${YELLOW}⏳ You should see (venv) in your terminal prompt${NC}"
echo ""
read -p "Press Enter when activated..."
echo ""

# Step 4: Install dependencies
echo -e "${BLUE}STEP 4: Install Dependencies${NC}"
echo "Run this command:"
echo ""
echo "  pip install -r requirements.txt"
echo ""
echo -e "${YELLOW}⏳ This will install: FastAPI, SQLAlchemy, Pydantic, etc.${NC}"
echo ""
read -p "Press Enter when installation is complete..."
echo ""

# Step 5: Initialize database
echo -e "${BLUE}STEP 5: Initialize Database${NC}"
echo "Run this command:"
echo ""
echo "  python database.py"
echo ""
echo -e "${YELLOW}⏳ This creates the SQLite database with all tables${NC}"
echo ""
read -p "Press Enter when database is initialized..."
echo ""

# Step 6: Start services
echo -e "${BLUE}STEP 6: Start the Three Services${NC}"
echo ""
echo "You need THREE terminal windows (tabs). In each one:"
echo ""
echo -e "${GREEN}Terminal 1 - Public Service (Port 8001)${NC}"
echo "  python app.py public"
echo ""
echo -e "${GREEN}Terminal 2 - Company Service (Port 8003)${NC}"
echo "  python app.py company"
echo ""
echo -e "${GREEN}Terminal 3 - Admin Service (Port 8004)${NC}"
echo "  python app.py admin"
echo ""
echo -e "${YELLOW}⏳ Open 3 new terminal tabs and run each command above${NC}"
echo ""
read -p "Press Enter when all 3 services are running..."
echo ""

# Step 7: Test the services
echo -e "${BLUE}STEP 7: Verify Services are Running${NC}"
echo ""
echo "Run these commands to test (in a 4th terminal):"
echo ""
echo "  curl http://localhost:8001/health"
echo "  curl http://localhost:8003/health"
echo "  curl http://localhost:8004/health"
echo ""
echo -e "${YELLOW}⏳ You should see: {\"status\":\"healthy\"...}${NC}"
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 8: Access API documentation
echo -e "${BLUE}STEP 8: Access API Documentation${NC}"
echo ""
echo "Open these URLs in your web browser:"
echo ""
echo -e "${GREEN}Public Service${NC}: http://localhost:8001/docs"
echo -e "${GREEN}Company Service${NC}: http://localhost:8003/docs"
echo -e "${GREEN}Admin Service${NC}: http://localhost:8004/docs"
echo ""
echo -e "${YELLOW}⏳ You'll see interactive API documentation (Swagger UI)${NC}"
echo ""
read -p "Press Enter to see API examples..."
echo ""

# Step 9: API Examples
echo -e "${BLUE}STEP 9: Try Your First API Call${NC}"
echo ""
echo -e "${GREEN}Example 1: Get all ads${NC}"
echo "  curl http://localhost:8001/api/ads"
echo ""
echo -e "${GREEN}Example 2: Register a user${NC}"
echo "  curl -X POST http://localhost:8001/api/register \\"
echo "    -H \"Content-Type: application/json\" \\"
echo "    -d '{\"email\":\"user@example.com\",\"password\":\"password123\",\"full_name\":\"John Doe\"}'"
echo ""
echo -e "${GREEN}Example 3: Get platform stats${NC}"
echo "  curl http://localhost:8001/api/dashboard_stats"
echo ""
echo -e "${YELLOW}⏳ Copy and paste these commands to test${NC}"
echo ""
read -p "Press Enter to see the file structure..."
echo ""

# Step 10: File structure
echo -e "${BLUE}STEP 10: Understanding the Code${NC}"
echo ""
echo "The main files you need to know:"
echo ""
echo "  app.py           - Main FastAPI application (all 3 services)"
echo "  models.py        - Database models (Users, Companies, Ads, etc)"
echo "  auth.py          - Authentication & authorization"
echo "  schemas.py       - Request/response validation"
echo "  database.py      - Database configuration"
echo "  requirements.txt - Python dependencies"
echo ""
echo "Documentation files:"
echo ""
echo "  README.md             - Setup & API reference"
echo "  MIGRATION_GUIDE.md    - How to migrate from PHP"
echo "  SUMMARY.md            - Project overview"
echo ""
echo -e "${YELLOW}⏳ Read README.md for detailed documentation${NC}"
echo ""
read -p "Press Enter to see common tasks..."
echo ""

# Step 11: Common tasks
echo -e "${BLUE}STEP 11: Common Tasks${NC}"
echo ""
echo -e "${GREEN}TO VIEW API DOCUMENTATION:${NC}"
echo "  Open http://localhost:8001/docs in your browser"
echo ""
echo -e "${GREEN}TO STOP SERVICES:${NC}"
echo "  Press Ctrl+C in each terminal"
echo ""
echo -e "${GREEN}TO START AGAIN:${NC}"
echo "  python app.py public (and same for company & admin)"
echo ""
echo -e "${GREEN}TO RESET DATABASE:${NC}"
echo "  rm python_shared/database/adsphere.db"
echo "  python database.py"
echo ""
echo -e "${GREEN}TO VIEW LOGS:${NC}"
echo "  Check the terminal output (logs are printed there)"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              You're Ready to Start!                        ║"
echo "║                                                            ║"
echo "║  Public Service:  http://localhost:8001                   ║"
echo "║  Company Service: http://localhost:8003                   ║"
echo "║  Admin Service:   http://localhost:8004                   ║"
echo "║                                                            ║"
echo "║  API Docs: http://localhost:8001/docs                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

